### PR TITLE
Added is_simplified_exception configuration option.

### PR DESCRIPTION
**Pull request by felixchenier**
Hi @leycec 

Even if I've been silent during the last months, I have been following beartype since I'm still thinking of using it for my library. And now that you published this https://github.com/beartype/beartype/discussions/299 I had a quick reaction that resemble this:

[silence, theater lights close, Félix enters the stage]

"Oh shit. My own little dirty simili-type checker that does an okay job needs all types to be stringified, and that's why I was using `from __future__ import annotations` everywhere. Now I'm back to square one. $/%"&?|!/. Oh god, I think it's time to adopt beartype and stop thinking about it. But I still have these issues that prevent me from using it: #216 #234"

[crowd applauses]

So I decided to dive a bit and created a new configuration option "is_simplified_exception" that solves both issues.

With is_simplified_exception False (default):
```
BeartypeCallHintParamViolation: Method kineticstoolkit.timeseries.TimeSeries.get_ts_after_time()
parameter time='allo' violates type hint <class 'float'> under non-default configuration 
BeartypeConf(claw_is_pep526=True, is_color=None, is_debug=False, is_simplified_exception=False, 
is_pep484_tower=True, strategy=<BeartypeStrategy.O1: 2>, warning_cls_on_decorator_exception=<class 
'beartype.roar._roarwarn.BeartypeClawDecorWarning'>), as str 'allo' not float or int.
```

Standard reaction: Oh, that seems serious, I think I need to reinstall my python environment.

With is_simplified_exception True:
```
TypeError: Method kineticstoolkit.timeseries.TimeSeries.get_ts_after_time() parameter time='allo'
was expected to be of type <class 'float'>.
```

Standard reaction: Oh, I wrote a string instead of a float. My bad.

To be honest, I really don't know what you will think of this pull request, and I'll be perfectly okay if you decide to do nothing with it. It may serve as a starting point for a solution that is less hacky, in case you do find it hacky. But I think it has value since it doesn't serve the same public. The default is perfect for software developers, and the simplified version would be better for the users of a library.

I'll be very curious to know what you think of it.

One last thing, I didn't edit any docstring. I guess that if you accept this PR, many docstrings will need to be changed since both options don't raise the same exception.

### CODE REVIEW

**Comment by felixchenier** [comment]
@leycec Maybe you'd prefer to separate those two features, I think I personally would, but then it may be too many configuration options. Anyway, if you want I can work on it. For instance:

```
is_simplified_exception_message=False
(or is_extended_exception_message=True)

is_raising_type_error=False
(or is_raising_beartype_exceptions=True)
```

**Comment by leycec** [comment]
> [silence, theater lights close, Félix enters the stage]



> My own little dirty simili-type checker that does an okay job...

Oh... Oh, Gods. What you done to yourself, Félix!?!? \*WHAT HAVE YOU DONE!?!?\* `</breaths_heavily_into_paper_bag>`


<sup>calm down, @leycec. calm down. just pretend you didn't read that and everything will be kk.</sup>

What I meant to say was... Thanks so much for this superbly *awesome* PR, Félix! You're totally right about everything, of course. I truly meant to do something about your prior feature requests, but I didn't. Now here we are. @beartype's existing violation messages are pretty awful, aren't they? This substring is especially bad and responsible for most of the badness:

```python
...under non-default configuration
BeartypeConf(claw_is_pep526=True, is_color=None, is_debug=False, is_simplified_exception=False, 
is_pep484_tower=True, strategy=<BeartypeStrategy.O1: 2>, warning_cls_on_decorator_exception=<class 
'beartype.roar._roarwarn.BeartypeClawDecorWarning'>)
```

Literal logorrhoea. Thus, I vomit into an offscreen bit-bucket. :vomiting_face: 

Also, this classic user reaction:

> Standard reaction: Oh, that seems serious, I think I need to reinstall my python environment.

:smile: :laughing:  :rofl: -> :sweat: :cry: :sob: 

> Maybe you'd prefer to separate those two features, I think I personally would, but then it may be too many configuration options. Anyway, if you want I can work on it.

**Yes!** Please! Gods! So much "Yes"!!! `</ahem>`

I know you've already invested a gargantuan pile of volunteer work into this. But... would you mind separating those two features out? You don't *have* to, of course. You've already done enough. I'm happy to have a go at this myself. But if you *do* find a spare moment to separate them out, that would be super and amazing.

## Let Us Now Bikeshed About Option Names

I am a weirdo. Therefore, I am fond of the following options:

* `violation_param_type: typing.Type[Exception]] = beartype.roar.BeartypeCallHintParamViolation` and `violation_return_type: typing.Type[Exception]] = beartype.roar.BeartypeCallHintReturnViolation`. Rather than pass a somewhat limited boolean option like either `is_raising_type_error` or `is_raising_beartype_exceptions`, callers should be permitted to pass full-blown options like `violation_param_type` and `violation_return_type` that accept actual exception types. If unpassed, these options would simply default to the custom exception types that @beartype currently raises, meaning: "Do whatever you think is best, @beartype. You do you."
* `violation_is_verbose: bool = True` instead of either `is_simplified_exception_message` or `is_extended_exception_message`, maybe? It's all subjective, of course. There is no wrong answer here. That said, I expect @beartype to eventually support a whole raft of violation-specific configuration options. Prefixing these options by the substring "`violation_`" should improve readability, discoverability, and disambiguity. Naturally, I have no idea what I'm talking about.

Given the above, this is what you might configure @beartype with:

```python
BeartypeConf(violation_is_verbose=False, violation_param_type=TypeError, violation_return_type=TypeError, ...)
```

Does that sound reasonable? Both should require only trivial changes to `get_beartype_violation()`. If major surgery is needed, **abort mission immediately and panic.**

## Yet Again, Ontario Thanks You

Thanks yet again for all you've done here, Félix. So much :love_hotel:! Yes, that is the love hotel emoji.

I'll merge this directly after you give the go-ahead that you're fully satisfied. This will probably land in our upcoming @beartype 0.17.0 release, whose release has yet to be decided but will probably happen within a month. Possibly. Maybe.

**Question:** do you need this functionality super-fast? If so, I'll speed up our release schedule. If not, I'll be lazy and just play video games for the entire month of November. This is what it means to live in Ontario. Quebec makes the video games. Ontario plays them. Truly, a partnership in heaven.

**Comment by felixchenier** [comment]
> Oh... Oh, Gods. What you done to yourself, Félix!?!?

Mmmmm, probably what I thought was the best at the time 😃 . When I did it, postponed annotations were supposed to become default "in a few weeks" in Python 3.10. And it's easy to parse a string when you're the one that creates the string in a first place. But I was wrong, obviously, and I need a proper type checker. Really, I'm still surprised that there are so few real-time type checkers out there. I have difficulty accepting that people in general are fine with raising obscure, really deep exceptions that make no sense, just because the toplevel function argument was the wrong type. Anyway, I don't need to convince you of course.

> I know you've already invested a gargantuan pile of volunteer work into this. But... would you mind separating those two features out? 

Gargantuan? No. I just did a multi-file search of "violates type hint" and I found the file that generates the strings. The end.

Really, It'll be a pleasure. It's not often obvious how we can help in an open source project that is not ours, and I know that I **can** do this boring refactoring, so I'll do it proudly. And really, I do it for me. The little time I put on it will save me tons of time later on my library.

> Let Us Now Bikeshed About Option Names. I am a weirdo.

Weirdo, I don't know. Maybe for your passion in finding weird animated gifs for anything, but apart from it...

I was **expecting** you to decide on option naming. The API of a module is so important. Just next in importance after "does the module work", and for me it's one of the very few creative parts of programming. An API is an art. You won't tell Elton John that he should wear white glasses instead of pink ones, so I won't tell @leycec that he should use my naming suggestions.

But I do have a suggestion. Instead of `violation_is_verbose: bool = True`, what about `violation_verbosity: int = 5`? For instance:

1. Minimal verbosity (aimed for API users) <--- My proposition in this PR
2. Reserved for later, currently same as 1
3. Extended verbosity (aimed for software developers). Provides more details on the exact cause of type hint violation.
4. Reserved for later, currently same as 3
5. Full verbosity. Like 3, but with additional information on current configuration settings. Default is 5.

> If major surgery is needed, abort mission immediately and panic.

Of course! But it's gonna be fine. Oh, wait a bit, my nose is bleeding. I'll be back.

> do you need this functionality super-fast?

Absolutely not. When I'm done with it, I'll still need to work on my library to switch to beartype. And I don't plan to do a release myself in the next month. Game in peace.

**Comment by felixchenier** [comment]
Hi @leycec 

I guess this is it! Need to run unit tests though. And line 413 of errormain.py is ugly. A standard exception do not have keyword arguments, therefore trying this with a standard exception fails with a TypeError. This code works, I don't know if it's robust enough though.

**Comment by leycec** [comment]
**WOW.** I'm stunned, Félix.

I receive one phenomenal PR per year. Last year, it was Harvard microscopist @tlambert03 with his object-oriented `beartype.door` API (which then became the basis for [Plum](https://github.com/beartype/plum)). This year, it is you with these shocking improvements to our exception-handling `BeartypeConf` API. Insanely impressive engineering. Take all my hand claps! All of them! :clap: :clap: :clap: :clap: :clap: :clap: :clap: 

Technically, I copy-pasted those emoji repeatedly. Pragmatically, I actually clapped that many times in real life for dramatic emphasis. My palms are now raw, red, and sore. Pretty sure it was worth it.

> Really, I'm still surprised that there are so few real-time type checkers out there.

*...heh.* You and me both, bro. The silence is deafening. I hear crickets when I code.

Interesting, there *were* quite a few competing type checkers in this space at one time. All of them except @beartype and [typeguard](https://github.com/agronholm/typeguard) quietly expired. Their authors gave up; their projects caved in; their packages lay scattered; their users long fled.

Only the stubborn survive in this hellish landscape of mangled APIs, broken PEPs, and failed promises.

> I have difficulty accepting that people in general are fine with raising obscure, really deep exceptions that make no sense, just because the toplevel function argument was the wrong type.

**Please accept the painful truth.** Félix, I've long since abandoned any pretence at understanding humanity. I love and adore humanity, but I'll never truly *understand* humanity. The dark legacies of duck typing and ["Easier to Ask for Forgiveness than Permission (EAFP)](https://realpython.com/python-lbyl-vs-eafp) cast a long shadow... even today. Most Pythonistas inherited a much more "hack it until you make it" mentality than ~~typing masochists~~ scientific chads such as ourselves.

The prevalence of artificial intelligence is rapidly changing even this, though. AI isn't "just" a [near trillion dollar industry](https://www.precedenceresearch.com/artificial-intelligence-market); it's the next iteration of industrial civilization. Entire professions, praxes, and economies are now at stake – and Python looms at the forefront. The stakes? Kinda high. Python's "old ways" are no longer acceptable. They never were, really. But it was easier to ignore the negative externalities caused by duck typing and EAFP (like unreadable exceptions, undebuggable code, and unintrospectable APIs) when the stakes were alot lower.

Thankfully, the old ways are fading fast. Let's light the way to a sane future full of happy AI that heartily claps us on the back.

> It's not often obvious how we can help in an open source project that is not ours, and I know that I can do this boring refactoring, so I'll do it proudly.

You're extraordinarily humble. I *love* that. Capitalism incentives pride posture and the [Dunning–Kruger effect](https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect). Humility is a rare and glistening jewel amidst the steaming refuse pile.

You are that jewel. Shine, Félix! Shine on, you crazy GitHub diamond. :sparkles: :gem: :sparkles: 

> An API is an art.

**OMG!** You get it! Yes, you get it! You win the Internet today! Indeed, all of Computer Science is but an art. We're all making this up as we go – so let's make the most of the keyboard in our hands and change this world. One artful API at a time.

> But I do have a suggestion. Instead of `violation_is_verbose: bool = True`, what about `violation_verbosity: int = 5`?

*...heh.* You're shockingly clever. Also, you're apparently telepathic. I was thinking along similar lines – but didn't want to impose too heavily on your *really* valuable time. Thankfully, you outpaced me and [did everyone a solid](https://www.quora.com/Where-did-the-phrase-do-me-a-solid-come-from) by intuitively going there anyway.

You have future-proofed @beartype. Therefore, @beartype again thanks you. :clap: :bear: :clap: 

> Absolutely not. When I'm done with it, I'll still need to work on my library to switch to beartype. And I don't plan to do a release myself in the next month. Game in peace.

**Superbness!** Thanks for being so accommodating. Your patience gives me valuable time to better support [PEP 695 (i.e., Python 3.12's new `type` syntax)](https://github.com/beartype/beartype/issues/297) in @beartype 0.17.0.

Please prod me if I've failed to release @beartype 0.17.0 by the time you need it. Shockingly, I promise to do something.

> I guess this is it! Need to run unit tests though.

And... **you've failed!** Just kidding. Tests are failing – but only because [`pyright` hates everybody](https://github.com/beartype/beartype/actions/runs/6779465747/job/18550889638?pr=301):

```
pyright 1.1.335, node v20.8.1, pyright-action 1.7.1
/home/runner/runners/2.311.0/externals/node20/bin/node /opt/hostedtoolcache/pyright/1.1.335/x64/package/index.js --pythonversion 3.8 --outputjson
/home/runner/work/beartype/beartype/beartype/_decor/error/errormain.py:410:13 - error: No parameter named "message" (reportGeneralTypeIssues)
Error: No parameter named "message" (reportGeneralTypeIssues)
/home/runner/work/beartype/beartype/beartype/_decor/error/errormain.py:411:13 - error: No parameter named "culprits" (reportGeneralTypeIssues)
Error: No parameter named "culprits" (reportGeneralTypeIssues)
/home/runner/work/beartype/beartype/beartype/_decor/error/errormain.py:420:12 - error: Expression of type "Exception" cannot be assigned to return type "type[Exception]"
  Type "Exception" cannot be assigned to type "type[Exception]" (reportGeneralTypeIssues)
Error: Expression of type "Exception" cannot be assigned to return type "type[Exception]"
  Type "Exception" cannot be assigned to type "type[Exception]" (reportGeneralTypeIssues)
3 errors, 0 warnings, 0 informations
Error: 3 errors
```

Static type-checkers hate duck typing. Thankfully, I hate static type-checkers. Shut *up*, static type-checkers. I could care less what they think, because they are broken, obsolete, and dumb.

I'm merging this anyway. I'll silence `pyright` and mypy with a subsequent commit. I'll also:

* Officially document these *wondrous* additions in [@beartype's ReadTheDocs (RTD)-hosted docos](https://beartype.readthedocs.io/en/latest/).
* Extensively unit test this functionality in our test suite with additional... tests.

> And line 413 of `errormain.py` is ugly. A standard exception does not have keyword arguments, therefore trying this with a standard exception fails with a `TypeError`. This code works, I don't know if it's robust enough though.

*...heh.* It's shockingly simple, but therefore clever. It's also duck typing, which I usually hate. But duck typing is probably a good fit for this particular use case, because we'd like to allow users the flexibility of either conforming to CPython's standard exception hierarchy or @beartype's "unique" `beartype.roar` exception hierarchy.

Actually... I think I might codify this with a new @beartype-specific abstract exception mixin resembling:

```python
# In "beartype.roar":
class BeartypeViolationMixin(object):
    def __init__(self, message: str, culprits: tuple) -> None:
        raise NotImplementedError('Implement me or suffer unspecified badness, you.')

    @property
    def culprits(self) -> tuple:
        raise NotImplementedError('Ditto.')

class BeartypeCallHintViolation(BeartypeCallHintException, BeartypeViolationMixin):
    ...
```

Then we just lightly refactor 413 of `errormain.py` to resemble:

```python
    exception = (
        exception_cls(
            message=exception_message,
            culprits=tuple(violation_culprits),
        )
        if issubclass(exception_cls, BeartypeViolationMixin) else
        # Standard exceptions do not have arguments.
        exception_cls(exception_message)
    )
```

That should also satisfy noxious `pyright` complaints about this. Be quiet, `pyright`. We have spoken.

Thanks *so* much for the tremendous effort, Félix. Let us merge this immediately before I inevitably break everything with half-baked ideas that ultimately crumble into dust like that Nazi dude at the end of that one Indiana Jones film. <sup>Actually, I'm pretty sure that's the end of *every* Indiana Jones film.</sup>

every time

**Pull request merged**
